CoreExercise/Controllers/TagHelpersController.cs
using CoreExercise.IService;
using CoreExercise.Models;
using CoreExercise.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace CoreExercise.Controllers
{
    public class TagHelpersController : Controller
    {
        //C# 6.0 - Auto Property Initializer
        public List<Hero> heros { get; } = new List<Hero>
        {
            new Hero { Name = "Elon Musk", Brief="特斯拉創辦人 伊隆·馬斯克", Photo="ElonMusk.jpg", WikiUrl="https://goo.gl/46xeXx" },
            new Hero { Name = "Mark Zuckerberg", Brief="Facebook創辦人 馬克·祖伯克", Photo="MarkZuckerberg.jpg", WikiUrl="https://goo.gl/BktGGA" },
            new Hero { Name = "Steve Jobs", Brief="蘋果創辦人 史提夫·賈伯斯", Photo="SteveJobs.jpg", WikiUrl="https://goo.gl/nAiX0y" },
            new Hero { Name = "Vader", Brief="帝國元帥  維達", Photo="Vader.jpg", WikiUrl="https://en.wikipedia.org/wiki/Darth_Vader" },
            new Hero { Name = "Darth Mual", Brief="星際大戰 達斯摩", Photo="DarthMual.jpg", WikiUrl="https://goo.gl/5obLhX"},
            new Hero { Name = "White Twilek", Brief="星際大戰 女絕地武士Twilek", Photo="WhiteTwilek.jpg", WikiUrl="https://goo.gl/reKzAu" },
            new Hero { Name = "Obiwan", Brief="星際大戰 歐比旺Obiwan", Photo="Obiwan.jpg", WikiUrl="http://bit.ly/33gxdgt" },
            new Hero { Name = "Merkel", Brief="德國總理 梅克爾", Photo="Merkel.jpg", WikiUrl="http://bit.ly/33huSlv" }
        };

        public IActionResult PartialTagHelper()
        {
            return View(heros);
        }

        public IActionResult SelectTagHelper()
        {
            var model = new CountryViewModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SelectTagHelper(CountryViewModel countryVM)
        {
            if (ModelState.IsValid)
            {
                //讀取國家代碼
                string countryCode = countryVM.Country;

                //由國家代碼查詢名稱
                string country = countryVM.Countries.Where(c => c.Value == countryCode).Select(x => x.Text).FirstOrDefault();

                return RedirectToAction("DisplayCountry", new { Country = country });
            }

            return View(countryVM);
        }

        //顯示Country資訊
        public IActionResult DisplayCountry(string country)
        {
            if (string.IsNullOrEmpty(country))
            {
                return Content("必須提供Country參數!");
            }

            ViewData["Country"] = country;

            return View();
        }

        public IActionResult SelectEnum()
        {
            var model = new CountryEnumViewModel();

            //以下是設定列舉預設值
            //model.EnumerateCountry = CountryEnum.France;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SelectEnum(int EnumerateCountry)
        {
            if (ModelState.IsValid)
            {
                //顯示Country名稱
                return RedirectToAction("DisplayCountry", new { Country = (CountryEnum)EnumerateCountry });
            }

            return View();
        }

        public IActionResult SelectOptionGroup()
        {
            //使用此功能, 必須先初始化CountryGroupViewModel模型類別
            var model = new CountryGroupViewModel();

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //按<select asp-for="Country" >的設定,接收參數應為string Country即可
        //但為何設定成CountryGroupViewModel型別物件? 因為其Countries會含有六個國家的List<SelectListItem>
        //它可用作LINQ將國家代碼轉換成國家全名, 而不必再額外初化CountryGroupViewModel物件來取得國家資訊
        public IActionResult SelectOptionGroup(CountryGroupViewModel countryVM)
        {
            if (ModelState.IsValid)
            {
                //將國家代碼轉換成國家全名
                var country = countryVM.Countries.Where(c => c.Value == countryVM.Country).Select(x => x.Text).FirstOrDefault();

                //顯示Country名稱
                return RedirectToAction("DisplayCountry", new { Country = country });
            }

            return View();
        }

        public IActionResult CacheTagHelper()
        {
            return View();
        }

        public IActionResult CustomTag()
        {
            return View();
        }
    }
}

CoreExercise/Views/TagHelpers/CacheTagHelper.cshtml
@{
    ViewData["Title"] = "CacheTagHelper";

    int counter = 1;
}

<div class="jumbotron">
    <h2>Cache Tag Helper</h2>
</div>


<div class="alert alert-success">@(counter++).@("<cache>")快取(快取過期預設為20分鐘)</div>
<cache>
    目前時間: @DateTime.Now
</cache>


<div class="alert alert-success">@(counter++). enable啟用</div>
<cache enabled="false">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). expire-on指定絕對過期日期</div>
<cache expires-on="@new DateTime(2025,3,28,12,30,0)">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). expire-after於首次快取內容後多少時間過期(預設為20分鐘)</div>
<cache expires-after="@TimeSpan.FromSeconds(120)">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). expire-sliding設定快取項目的值多久未被存取就會過期</div>
<cache expires-sliding="@TimeSpan.FromSeconds(60)">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). vary-by-header在標頭值改變時會觸發快取重新整理</div>
<cache vary-by-header="User-Agent">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). vary-by-query依查詢字串的改變,而觸發快取重新整理</div>
<cache vary-by-query="refresh,clean">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). vary-by-route依路由參數改變,而觸發快取重新整理</div>
<cache vary-by-route="id">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). vary-by-cookie依cookie的改變,而觸發快取重新整理</div>
<cache vary-by-cookie=".AspNetCore.Identity.Application">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). vary-by-user依@User.Identity.Names改變,而觸發快取重新整理</div>
<cache vary-by-user="true">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). vary-by當屬性字串值所參考的物件變更,而觸發快取重新整理</div>
<cache vary-by="@Model">
    目前時間: @DateTime.Now
</cache>

<div class="alert alert-success">@(counter++). priority設定快取保留的優先權層級(High, Low, NeverRemove, Normal預設)</div>
<cache priority="@Microsoft.Extensions.Caching.Memory.CacheItemPriority.High">
    目前時間: @DateTime.Now
</cache>


@section topCSS
{
    <link href="~/css/alertbar.css" rel="stylesheet" />
}

CoreExercise/Views/TagHelpers/CustomTag.cshtml
@{
    ViewData["Title"] = "CustomTag";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CustomTag</h1>

<email mail-to="services"></email>

CoreExercise/Views/TagHelpers/DisplayCountry.cshtml
@{
    ViewData["Title"] = "DisplayCountry";
}


你選擇的國家為: @ViewData["Country"]

<br /><br />

<a href="@ViewContext.HttpContext.Request.Headers["Referer"].ToString()" class="btn btn-primary">Back返回上一頁</a>

CoreExercise/Views/TagHelpers/PartialTagHelper.cshtml
@model IEnumerable<Hero>

@{
    ViewData["Title"] = "PartialTagHelper";

    ViewData["Caption"] = "英雄人物";

    int counter = 1;
}

<h1>PartialTagHelper</h1>

<div class="alert alert-success">@(counter++). 呼叫Partial View</div>
<partial name="_HeroPartial" />

<div class="alert alert-success">@(counter++). 呼叫Partial View, 用view-data屬性傳遞ViewData</div>
<partial name="_HeroPartial" view-data="ViewData" />

<div class="alert alert-success">@(counter++). 呼叫Partial View, 用model屬性傳遞model模型實例</div>
<partial name="_HeroPartial" model="Model" />


<div class="alert alert-success">@(counter++). 呼叫Partial View, 用for屬性傳遞model模型實例</div>
<partial name="_HeroPartial" for="@Model" />

<div class="alert alert-success">@(counter++). 呼叫Partial View, 同時model模型實例&傳遞ViewData</div>
<partial name="_HeroPartial" model="@Model" view-data="ViewData" />


@section topCSS
{
    <link href="~/css/hero.css" rel="stylesheet" />
    <link href="~/css/alertbar.css" rel="stylesheet" />
}

CoreExercise/Views/TagHelpers/SelectEnum.cshtml
@model CountryEnumViewModel

@{
    ViewData["Title"] = "SelectEnum";
}

<h1>SelectEnum</h1>

<form asp-controller="TagHelpers" asp-action="SelectEnum" method="post">
    <select asp-for="EnumerateCountry" asp-items="Html.GetEnumSelectList<CountryEnum>()">
        <option value="">==請選擇國家==</option>
    </select>
    <span asp-validation-for="EnumerateCountry" class="text-danger"></span>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section endJS
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

CoreExercise/Views/TagHelpers/SelectOptionGroup.cshtml
@model CountryGroupViewModel
@{
    ViewData["Title"] = "SelectOptionGroup";
}

<h1>SelectOptionGroup</h1>

<form asp-controller="TagHelpers" asp-action="SelectOptionGroup" method="post">
    <select asp-for="Country" asp-items="Model.Countries">
    </select>
    <span asp-validation-for="Country" class="text-danger"></span>
    <br /><br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CoreExercise/Views/TagHelpers/SelectTagHelper.cshtml
@model CountryViewModel
@{
    ViewData["Title"] = "SelectTagHelper";

}

<h1>SelectTagHelper</h1>

<form asp-controller="TagHelpers" asp-action="SelectTagHelper" method="post">
    <label asp-for="Country"></label>
    <select asp-for="Country" asp-items="Model.Countries">
        <option value="">==請選擇國家==</option>
    </select>
    <span asp-validation-for="Country" class="text-danger"></span>
    <br /><br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section endJS
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}